title: Whitenoise drum beat effect
hero_image: images/banner.png
description: Whitenoise drum beat effect
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Whitenoise drum beat effect
